#!/bin/bash
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get install nano -y
sudo apt-get install gedit -y
sudo apt-get install default-jre
sudo apt-get install eclipse -y
sudo apt-get install ros-melodic-ros-tutorials -y
sudo apt-get install python-rosinstall python-rosinstall-generator python-wstool build-essential -y
sudo apt-get install ros-melodic-roslz4 -y
sudo apt-get install ros-melodic-roslz4-dbgsym -y
sudo apt-get install ros-melodic-rosmake -y
sudo apt-get install ros-melodic-rosmaster -y
sudo apt-get install ros-melodic-rosmon -y
sudo apt-get install ros-melodic-rosmon-core -y
sudo apt-get install ros-melodic-rosmon-core-dbgsym -y
sudo apt-get install ros-melodic-rosmon-msgs -y
sudo apt-get install ros-melodic-rosmsg -y
sudo apt-get install ros-melodic-rosnode -y
sudo apt-get install ros-melodic-rosout -y
sudo apt-get install ros-melodic-rosout-dbgsym -y
sudo apt-get install ros-melodic-rospack -y
sudo apt-get install ros-melodic-rospack-dbgsym -y
sudo apt-get install ros-melodic-rosparam -y
sudo apt-get install ros-melodic-rosparam-handler -y
sudo apt-get install ros-melodic-rosparam-shortcuts -y
sudo apt-get install ros-melodic-rosparam-shortcuts-dbgsym -y
sudo apt-get install ros-melodic-rospatlite -y
sudo apt-get install ros-melodic-rospilot -y
sudo apt-get install ros-melodic-rospilot-dbgsym -y
sudo apt-get install ros-melodic-rosping -y
sudo apt-get install ros-melodic-rosping-dbgsym -y
sudo apt-get install ros-melodic-rospy -y
sudo apt-get install ros-melodic-rospy-message-converter -y
sudo apt-get install ros-melodic-rospy-tutorials -y
sudo apt-get install ros-melodic-rosserial -y
sudo apt-get install ros-melodic-rosserial-arduino -y
sudo apt-get install ros-melodic-rosserial-client -y
sudo apt-get install ros-melodic-rosserial-embeddedlinux -y
sudo apt-get install ros-melodic-rosserial-mbed -y
sudo apt-get install ros-melodic-rosserial-msgs -y
sudo apt-get install ros-melodic-rosserial-python -y
sudo apt-get install ros-melodic-rosserial-server -y
sudo apt-get install ros-melodic-rosserial-server-dbgsym -y
sudo apt-get install ros-melodic-rosserial-windows -y
sudo apt-get install ros-melodic-rosservice -y
sudo apt-get install ros-melodic-rostate-machine -y
sudo apt-get install ros-melodic-rostate-machine-dbgsym -y
sudo apt-get install ros-melodic-rostest -y
sudo apt-get install ros-melodic-rostime -y
sudo apt-get install ros-melodic-rostime-dbgsym -y
sudo apt-get install ros-melodic-rostopic -y
sudo apt-get install ros-melodic-roswtf -y
sudo apt-get install ros-melodic-roswww -y
sudo apt-get install ros-melodic-rotate-recovery -y
sudo apt-get install ros-melodic-rotate-recovery-dbgsym -y
sudo apt-get install ros-melodic-rplidar-ros -y
sudo apt-get install ros-melodic-rplidar-ros-dbgsym -y
sudo apt-get install ros-melodic-rqt -y
sudo apt-get install ros-melodic-rqt-action -y
sudo apt-get install ros-melodic-rqt-bag -y
sudo apt-get install ros-melodic-rqt-bag-plugins -y
sudo apt-get install ros-melodic-rqt-common-plugins -y
sudo apt-get install ros-melodic-rqt-console -y
sudo apt-get install ros-melodic-rqt-controller-manager -y
sudo apt-get install ros-melodic-rqt-dep -y
sudo apt-get install ros-melodic-rqt-ez-publisher -y
sudo apt-get install ros-melodic-rqt-graph -y
sudo apt-get install ros-melodic-rqt-gui -y
sudo apt-get install ros-melodic-rqt-gui-cpp -y
sudo apt-get install ros-melodic-rqt-gui-cpp-dbgsym -y
sudo apt-get install ros-melodic-rqt-gui-py -y
sudo apt-get install ros-melodic-rqt-image-view -y
sudo apt-get install ros-melodic-rqt-image-view-dbgsym -y
sudo apt-get install ros-melodic-rqt-joint-trajectory-controller -y
sudo apt-get install ros-melodic-rqt-nav-view -y
sudo apt-get install ros-melodic-rqt-pose-view -y
sudo apt-get install ros-melodic-rqt-publisher -y
sudo apt-get install ros-melodic-rqt-py-common -y
sudo apt-get install ros-melodic-rqt-py-console -y
sudo apt-get install ros-melodic-rqt-service-caller -y
sudo apt-get install ros-melodic-rqt-shell -y
sudo apt-get install ros-melodic-rqt-srv -y
sudo apt-get install ros-melodic-rqt-tf-tree -y
sudo apt-get install ros-melodic-rqt-top -y
sudo apt-get install ros-melodic-rqt-topic -y
sudo apt-get install ros-melodic-rqt-web -y
sudo apt-get install ros-melodic-rslidar -y
sudo apt-get install ros-melodic-rslidar-driver -y
sudo apt-get install ros-melodic-rslidar-driver-dbgsym -y
sudo apt-get install ros-melodic-rslidar-msgs -y
sudo apt-get install ros-melodic-rslidar-pointcloud -y
sudo apt-get install ros-melodic-rslidar-pointcloud-dbgsym -y
sudo apt-get install ros-melodic-rviz -y
sudo apt-get install ros-melodic-rviz-dbgsym -y
sudo apt-get install ros-melodic-rviz-imu-plugin -y
sudo apt-get install ros-melodic-rviz-imu-plugin-dbgsym -y
sudo apt-get install ros-melodic-rviz-plugin-tutorials -y
sudo apt-get install ros-melodic-rviz-plugin-tutorials-dbgsym -y
sudo apt-get install ros-melodic-rviz-python-tutorial -y
sudo apt-get install ros-melodic-rviz-visual-tools -y
sudo apt-get install ros-melodic-rviz-visual-tools-dbgsym -y
sudo apt-get install ros-melodic-safety-limiter -y
sudo apt-get install ros-melodic-safety-limiter-dbgsym -y
sudo apt-get install ros-melodic-safety-limiter-msgs -y
sudo apt-get install ros-melodic-seed-smartactuator-sdk -y
sudo apt-get install ros-melodic-seed-smartactuator-sdk-dbgsym -y
sudo apt-get install ros-melodic-sensor-msgs -y
sudo apt-get install ros-melodic-serial -y
sudo apt-get install ros-melodic-serial-dbgsym -y
sudo apt-get install ros-melodic-shape-msgs -y
sudo apt-get install ros-melodic-simple-message -y
sudo apt-get install ros-melodic-simple-message-dbgsym -y
sudo apt-get install ros-melodic-simple-navigation-goals-tutorial -y
sudo apt-get install ros-melodic-simple-navigation-goals-tutorial-dbgsym -y
sudo apt-get install ros-melodic-simulators -y
sudo apt-get install ros-melodic-slam-gmapping -y
sudo apt-get install ros-melodic-slam-toolbox -y
sudo apt-get install ros-melodic-slam-toolbox-dbgsym -y
sudo apt-get install ros-melodic-sound-play -y
sudo apt-get install ros-melodic-speech-recognition-msgs -y
sudo apt-get install ros-melodic-std-capabilities -y
sudo apt-get install ros-melodic-std-msgs -y
sudo apt-get install ros-melodic-stereo-image-proc -y
sudo apt-get install ros-melodic-stereo-image-proc-dbgsym -y
sudo apt-get install ros-melodic-stereo-msgs -y
sudo apt-get install ros-melodic-teleop-tools -y
sudo apt-get install ros-melodic-teleop-tools-msgs -y
sudo apt-get install ros-melodic-teleop-twist-joy -y
sudo apt-get install ros-melodic-teleop-twist-joy-dbgsym -y
sudo apt-get install ros-melodic-teleop-twist-keyboard -y
sudo apt-get install ros-melodic-topic-tools -y
sudo apt-get install ros-melodic-topic-tools-dbgsym -y
sudo apt-get install ros-melodic-track-odometry -y
sudo apt-get install ros-melodic-track-odometry-dbgsym -y
sudo apt-get install ros-melodic-turtle-actionlib -y
sudo apt-get install ros-melodic-turtle-actionlib-dbgsym -y
sudo apt-get install ros-melodic-turtle-tf -y
sudo apt-get install ros-melodic-turtle-tf-dbgsym -y
sudo apt-get install ros-melodic-turtle-tf2 -y
sudo apt-get install ros-melodic-turtle-tf2-dbgsym -y
sudo apt-get install ros-melodic-turtlebot3 -y
sudo apt-get install ros-melodic-turtlebot3-applications -y
sudo apt-get install ros-melodic-turtlebot3-applications-msgs -y
sudo apt-get install ros-melodic-turtlebot3-automatic-parking -y
sudo apt-get install ros-melodic-turtlebot3-automatic-parking-vision -y
sudo apt-get install ros-melodic-turtlebot3-bringup -y
sudo apt-get install ros-melodic-turtlebot3-bringup-dbgsym -y
sudo apt-get install ros-melodic-turtlebot3-description -y
sudo apt-get install ros-melodic-turtlebot3-example -y
sudo apt-get install ros-melodic-turtlebot3-fake -y
sudo apt-get install ros-melodic-turtlebot3-fake-dbgsym -y
sudo apt-get install ros-melodic-turtlebot3-follow-filter -y
sudo apt-get install ros-melodic-turtlebot3-follower -y
sudo apt-get install ros-melodic-turtlebot3-gazebo -y
sudo apt-get install ros-melodic-turtlebot3-gazebo-dbgsym -y
sudo apt-get install ros-melodic-turtlebot3-msgs -y
sudo apt-get install ros-melodic-turtlebot3-navigation -y
sudo apt-get install ros-melodic-turtlebot3-panorama -y
sudo apt-get install ros-melodic-turtlebot3-panorama-dbgsym -y
sudo apt-get install ros-melodic-turtlesim -y
sudo apt-get install ros-melodic-turtlesim-dash -y
sudo apt-get install ros-melodic-turtlesim-dbgsym -y
sudo apt-get install ros-melodic-unique-id -y
sudo apt-get install ros-melodic-unique-identifier -y
sudo apt-get install ros-melodic-urdf -y
sudo apt-get install ros-melodic-urdf-dbgsym -y
sudo apt-get install ros-melodic-usb-cam -y
sudo apt-get install ros-melodic-usb-cam-controllers -y
sudo apt-get install ros-melodic-usb-cam-controllers-dbgsym -y
sudo apt-get install ros-melodic-usb-cam-dbgsym -y
sudo apt-get install ros-melodic-usb-cam-hardware -y
sudo apt-get install ros-melodic-usb-cam-hardware-dbgsym -y
sudo apt-get install ros-melodic-uuid-msgs -y
sudo apt-get install ros-melodic-xv-11-laser-driver -y
sudo apt-get install ros-melodic-xv-11-laser-driver-dbgsym -y